# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-10 13:30
from __future__ import unicode_literals

import com_presa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=com_presa.models.upload_location)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=com_presa.models.upload_location)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
